version: '3'
services:
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    ports:
      - "8080:8080"
    links:
      - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  broker:
    image: confluentinc/cp-kafka:7.4.6
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  flightpublisher:
    build: ./flight-publisher
    container_name: flightpublisher
    depends_on:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      FLIGHTSCRAPER_KAFKA_TOPIC: 'flights.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  flightpersistence:
    build: ./flight-persistence
    container_name: flightpersistence
    depends_on:
      - broker
    ports:
      - "8181:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      FLIGHTSCRAPER_KAFKA_TOPIC: 'flights.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  notification:
    build: ./notification
    container_name: notification
    depends_on:
      - broker
    ports:
      - "8282:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      FLIGHTSCRAPER_KAFKA_TOPIC: 'flights.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  subscriptionpersistence:
    build: ./subscription-persistence
    container_name: subscriptionpersistence
    ports:
      - "8383:8443"
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - flightpersistence
      - flightpublisher
      - notification
      - subscriptionpersistence

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true